### ISSUE TITLE
Current tarball fails  to build on Freebsd 10.3 

### ISSUE THREAD

**Issue by joshbaptiste** [pwoolcoc/theca#23]
Hi 
i'm attempting to build the current tarball release on FreeBSD 10.

```
bsd:~/Downloads/pwoolcoc-theca-9b520fa $ uname -a
FreeBSD bsd 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

bsd:~/Downloads/pwoolcoc-theca-9b520fa $ cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading docopt v0.6.82
 Downloading term v0.4.4
 Downloading tempdir v0.3.5
 Downloading rust-crypto v0.2.36
 Downloading strsim v0.3.0
 Downloading lazy_static v0.2.1
 Downloading gcc v0.3.28
   Compiling regex-syntax v0.3.3
   Compiling winapi v0.2.7
   Compiling utf8-ranges v0.1.3
   Compiling strsim v0.3.0
   Compiling libc v0.2.13
   Compiling memchr v0.1.11
   Compiling lazy_static v0.2.1
   Compiling rand v0.3.14
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling tempdir v0.3.5
   Compiling gcc v0.3.28
   Compiling time v0.1.35
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.6
   Compiling term v0.4.4
   Compiling aho-corasick v0.5.2
   Compiling regex v0.1.71
   Compiling rustc-serialize v0.3.19
   Compiling rust-crypto v0.2.36
   Compiling docopt v0.6.82
   Compiling theca v1.0.0 (file:///usr/home/j/Downloads/pwoolcoc-theca-9b520fa)
error[E0425]: unresolved name `TIOCGWINSZ`
   --> src/theca/utils.rs:107:30
    |
107 |         ioctl(STDOUT_FILENO, TIOCGWINSZ, &mut window as *mut Winsize);
    |                              ^^^^^^^^^^ unresolved name

error: aborting due to previous error

error: Could not compile `theca`.
```

**Comment by joshbaptiste** [comment]
TIOCGWINSZ looks to be defined without issue in /usr/include/sys/ttycom.h
```
bsd:~ $ cat > t.c
#include <stdio.h>
#include <sys/ioctl.h>

int main(int argc, char **argv) {
    struct winsize sz;

    ioctl(0, TIOCGWINSZ, &sz);
    printf("Screen width: %i  Screen height: %i\n", sz.ws_col, sz.ws_row);
    return 0;
}
bsd:~ $ clang t.c -o t
bsd:~ $ ./t
Screen width: 168  Screen height: 42
```
